# Generated by Django 4.0.2 on 2022-02-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(max_length=255)),
                ('anonymity', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('uptime', models.FloatField()),
                ('response', models.FloatField()),
                ('transfer', models.FloatField()),
            ],
        ),
    ]
