# Generated by Django 4.0.2 on 2022-02-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxylist',
            name='anonymity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='protocol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='response',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='transfer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxylist',
            name='uptime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
